version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    container_name: resource-container-1
    ports:
      - 5433:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=resource-password
      - POSTGRES_USER=resource
      - POSTGRES_DB=resource
      - PGDATA=/var/lib/postgresql/data/some_name/
